import turtle
turtle.pensize(5)
turtle.speed(1)
turtle.color("blue")
turtle.begin_fill()
turtle.fillcolor('red')
turtle.left(90)
turtle.forward(150)
turtle.setheading(-40)
turtle.forward(100)
turtle.setheading(180)
turtle.forward(60)
turtle.setheading(-30)
turtle.forward(150)
turtle.setheading(180)
turtle.forward(150)
turtle.end_fill()
turtle.mainloop()
