import turtle
turtle.pensize(5)
turtle.speed(1)
turtle.color("green")
turtle.begin_fill()
turtle.fillcolor("yellow")
turtle.left(150)
turtle.forward(180)
turtle.circle(-90,180)
turtle.setheading(60)
turtle.circle(-90,180)
turtle.forward(180)
turtle.left(-270)
turtle.backward(130)
turtle.setheading(50)
turtle.backward(120)
turtle.forward(460)
turtle.end_fill()
turtle.mainloop()

