import turtle
turtle.pensize(3)
turtle.color()
turtle.speed(1)
turtle.begin_fill()
turtle.setheading(90)
turtle.forward(150)
turtle.setheading(320)
turtle.forward(100)
turtle.setheading(180)
turtle.forward(70)
turtle.mainloop()
